// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type ApFollower struct {
	Iri       string
	Inbox     string
	Name      sql.NullString
	Username  string
	Image     sql.NullString
	CreatedAt sql.NullTime
}

type ApOutbox struct {
	ID        string
	Iri       string
	Value     []byte
	Type      string
	CreatedAt sql.NullTime
}
