// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type ApAcceptedActivity struct {
	ID        int64
	Iri       string
	Actor     string
	Type      string
	Timestamp time.Time
}

type ApFollower struct {
	Iri                      string
	Inbox                    string
	SharedInbox              sql.NullString
	Name                     sql.NullString
	Username                 string
	Image                    sql.NullString
	Request                  string
	CreatedAt                sql.NullTime
	ApprovedAt               sql.NullTime
	DisabledAt               sql.NullTime
	RequestObject            []byte
	LastValidatedAt          sql.NullTime
	FirstValidationFailureAt sql.NullTime
	Directory                sql.NullBool
}

type ApOutbox struct {
	Iri              string
	Value            []byte
	Type             string
	CreatedAt        sql.NullTime
	LiveNotification sql.NullBool
}

type Auth struct {
	ID        int64
	UserID    string
	Token     string
	Type      string
	Timestamp time.Time
}

type Datastore struct {
	Key       string
	Value     []byte
	Timestamp time.Time
}

type FederatedServer struct {
	ID                int64
	Iri               string
	Name              sql.NullString
	LogoUrl           sql.NullString
	IsOnline          sql.NullBool
	StreamTitle       sql.NullString
	StreamDescription sql.NullString
	StreamTags        sql.NullString
	ThumbnailUrl      sql.NullString
	LastSeenOnline    sql.NullTime
	LastStatusUpdate  sql.NullTime
	AddedAt           sql.NullTime
	FollowedAt        sql.NullTime
	Pending           sql.NullBool
	Username          sql.NullString
	DisplayName       sql.NullString
	Summary           sql.NullString
	AcceptedAt        sql.NullTime
	RejectedAt        sql.NullTime
	FollowStatus      sql.NullString
}

type IpBan struct {
	IpAddress string
	Notes     sql.NullString
	CreatedAt sql.NullTime
}

type Message struct {
	ID        string
	UserID    sql.NullString
	Body      sql.NullString
	EventType sql.NullString
	HiddenAt  sql.NullTime
	Timestamp sql.NullTime
	Title     sql.NullString
	Subtitle  sql.NullString
	Image     sql.NullString
	Link      sql.NullString
}

type Notification struct {
	ID          int64
	Channel     string
	Destination string
	CreatedAt   sql.NullTime
}

type User struct {
	ID              string
	DisplayName     string
	DisplayColor    int64
	CreatedAt       sql.NullTime
	DisabledAt      sql.NullTime
	PreviousNames   sql.NullString
	NamechangedAt   sql.NullTime
	AuthenticatedAt sql.NullTime
	Scopes          sql.NullString
	Type            sql.NullString
	LastUsed        sql.NullTime
}

type UserAccessToken struct {
	Token     string
	UserID    string
	Timestamp time.Time
}

type Webhook struct {
	ID        int64
	Url       string
	Events    string
	Timestamp sql.NullTime
	LastUsed  sql.NullTime
}
