// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type ApAcceptedActivity struct {
	ID        int32
	Iri       string
	Actor     string
	Type      string
	Timestamp time.Time
}

type ApFollower struct {
	Iri           string
	Inbox         string
	Name          sql.NullString
	Username      string
	Image         sql.NullString
	Request       string
	RequestObject []byte
	CreatedAt     sql.NullTime
	ApprovedAt    sql.NullTime
	DisabledAt    sql.NullTime
}

type ApOutbox struct {
	Iri              string
	Value            []byte
	Type             string
	CreatedAt        sql.NullTime
	LiveNotification sql.NullBool
}

type Auth struct {
	ID        int32
	UserID    string
	Token     string
	Type      string
	Timestamp time.Time
}

type IpBan struct {
	IpAddress string
	Notes     sql.NullString
	CreatedAt sql.NullTime
}

type Message struct {
	ID        string
	UserID    sql.NullString
	Body      sql.NullString
	EventType sql.NullString
	HiddenAt  sql.NullTime
	Timestamp sql.NullTime
	Title     sql.NullString
	Subtitle  sql.NullString
	Image     sql.NullString
	Link      sql.NullString
}

type Notification struct {
	ID          int32
	Channel     string
	Destination string
	CreatedAt   sql.NullTime
}

type User struct {
	ID              string
	DisplayName     string
	DisplayColor    int32
	CreatedAt       sql.NullTime
	DisabledAt      sql.NullTime
	PreviousNames   sql.NullString
	NamechangedAt   sql.NullTime
	Scopes          sql.NullString
	AuthenticatedAt sql.NullTime
	Type            sql.NullString
	LastUsed        interface{}
}

type UserAccessToken struct {
	Token     string
	UserID    string
	Timestamp time.Time
}
